### ISSUE TITLE
Measurement widget

### ISSUE THREAD

**Issue by MichelleJean28** [Esri/calcite-maps#150]
Could you provide the code for the Measurement widget? 
JS 4.x does not [support ](https://developers.arcgis.com/javascript/latest/guide/functionality-matrix/index.html) this widget, but it should work in calcite-maps JS 3.x.
Thank you!

**Comment by tmcgee** [comment]
Hi @MichelleJean28,

I encourage you to check out [my repo](https://github.com/tmcgee/cmv-calcite-maps) which integrates the open source project [CMV](https://github.com/cmv/cmv-app) (Configurable Map Viewer) with Calcite Maps. It includes the Esri Measurement widget as well as a number of other core widgets and many widgets [contributed](https://github.com/cmv/cmv-contrib-widgets) by the CMV community. I am one of the lead developers for the CMV project. The initial version of my repo uses the Esri JS API 3.x version as a proof of concept. I have another repo that integrates CMV, calcite maps and the Esri JS 4.x version that will soon be public. I plan to add more capabilities as CMV and Calcite Maps continue to evolve. I hope this helps.

**Comment by MichelleJean28** [comment]
Hi @tmcgee, 

Thank you, CMV with Calcite Maps looks really great with all these widgets.

I would like to use it as a web app template. Is there a way to automatically use the layers available in the web map? In [viewer.js](https://github.com/tmcgee/cmv-calcite-maps/blob/master/config/viewer.js) each layer has it's own URL inserted manually.

**Comment by tmcgee** [comment]
Hi @MichelleJean28,

Sure you can use a webmap. Full support for the current [webmap specification](https://developers.arcgis.com/web-map-specification/) was added to CMV a few months back. You just need to provide the [webMapId](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/viewer.js#L81-L82) in viewer.js. You can even mix and match layers and widgets defined in the webmap with additional operational layers and widgets within those sections of viewer.js.

A couple of additional comments...

1. If you are working with a Portal webmap instead of one at arcgis.com, you will need to change the [`arcgisurl`](https://developers.arcgis.com/javascript/3/jsapi/esri.arcgis.utils-amd.html#arcgisurl) from the default. I believe you can also retrieve the full webmap json from portal and just use that. I don't work with portal at all so not sure these approaches have been fully tested.

2. I noticed that another developer [commented out](https://github.com/cmv/cmv-app/blob/develop/viewer/js/config/app.js#L36) the webmap mixin in a recent update to cmv. (It needs to be un-commented at 3 places in that file) I have asked him if there is a reason for that. I suspect it unintentional and we'll have that remedied in the next few days.

If you need additional support with cmv and cmv-calcite-maps, we can support you within those GitHub repos or in our [Gitter chat room](https://gitter.im/cmv/cmv-app).

**Comment by alaframboise** [comment]
@tmcgee awesome work and thank you. I'll dig into this more after devsummit.

**Comment by alaframboise** [comment]
@MichelleJean28 We don't have a measurement widget quite yet for 4.x, but when it's available it will be here in the master4 branch.

https://github.com/Esri/arcgis-js-api/tree/4master

**Comment by MichelleJean28** [comment]
This has been very helpful, thank you @tmcgee for the quick and comprehensive support. You are doing a great job with CMV.

**Comment by MichelleJean28** [comment]
Thank you @alaframboise
