### ISSUE TITLE
Widget Colors are only light or dark and do not match rest of color theme when applied to all.

### ISSUE THREAD

**Issue by pcsswamin** [Esri/calcite-maps#193]
Would be nice if jsapi widget colors could match the rest of the calcite color theme as well.

![image](https://user-images.githubusercontent.com/11682688/36942996-b3607cfe-1f35-11e8-9311-9f72dc3432c4.png)

**Comment by alaframboise** [comment]
You could achieve this now by 1) overriding the widget background, foreground and hover states or by 2) setting the vars and recompiling the SASS https://github.com/Esri/calcite-maps/blob/master/lib/sass/support/arcgis-4.x.scss#L1. To apply dynamically like the UI components however is not realistic because there are too many classes and states to handle.

**Comment by pcsswamin** [comment]
Thanks Allan for the quick responses. Hope to chat with you in person this week. Please update if anything changes on this topic.. Leave it up to you to close or keep open.
